import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, "..");
const contractPath = path.join(rootDir, "packages/contracts/pollek-contract.json");
const sdkPath = path.join(rootDir, "packages/sdk/pollek-cloud-client.mjs");

export function sdkSource(contract) {
  const version = contract.contract_version;
  return `// Generated by scripts/generate-sdk.mjs from packages/contracts/pollek-contract.json.
// Keep this dependency-light so Local Pollek and Cloud tests can import it without a build step.

export const POLLEK_CONTRACT_VERSION = ${JSON.stringify(version)};

export class PollekCloudClient {
  constructor({ baseUrl, fetchImpl = globalThis.fetch, token = null } = {}) {
    if (!baseUrl) throw new Error("baseUrl is required");
    if (!fetchImpl) throw new Error("fetch implementation is required");
    this.baseUrl = String(baseUrl).replace(/\\/+$/, "");
    this.fetch = fetchImpl;
    this.token = token;
  }

  async request(path, { method = "GET", body, headers = {} } = {}) {
    const response = await this.fetch(\`\${this.baseUrl}\${path}\`, {
      method,
      headers: {
        "accept": "application/json",
        ...(body === undefined ? {} : { "content-type": "application/json" }),
        ...(this.token ? { "authorization": \`Bearer \${this.token}\` } : {}),
        ...headers
      },
      body: body === undefined ? undefined : JSON.stringify(body)
    });
    const text = await response.text();
    const payload = text ? JSON.parse(text) : null;
    if (!response.ok) {
      const error = new Error(payload?.error || \`Pollek Cloud HTTP \${response.status}\`);
      error.status = response.status;
      error.payload = payload;
      throw error;
    }
    return payload;
  }

  getContract() {
    return this.request("/.well-known/pollek-contract");
  }

  getOpenApi() {
    return this.request("/contracts/openapi.json");
  }

  getEventSchema() {
    return this.request("/contracts/events.schema.json");
  }

  getBundleManifestSchema() {
    return this.request("/contracts/bundle-manifest.schema.json");
  }

  getTelemetryEnvelopeSchema() {
    return this.request("/contracts/telemetry-envelope.schema.json");
  }

  getLcpUsageLedgerSchema() {
    return this.request("/contracts/lcp-usage-ledger.schema.json");
  }

  ingestTelemetry(path, request) {
    return this.request(path, { method: "POST", body: request });
  }

  ingestTelemetryBatch(request) {
    return this.ingestTelemetry("/v1/telemetry/batches", request);
  }

  ingestTelemetryEvent(request) {
    return this.ingestTelemetry("/v1/telemetry/events", request);
  }

  listTelemetryObservations({ tenantId = "" } = {}) {
    const suffix = tenantId ? \`?tenant_id=\${encodeURIComponent(tenantId)}\` : "";
    return this.request(\`/v1/telemetry/observations\${suffix}\`);
  }

  listTelemetryResources({ tenantId = "" } = {}) {
    const suffix = tenantId ? \`?tenant_id=\${encodeURIComponent(tenantId)}\` : "";
    return this.request(\`/v1/telemetry/resources\${suffix}\`);
  }

  getTelemetryEnforcementStatus({ tenantId = "" } = {}) {
    const suffix = tenantId ? \`?tenant_id=\${encodeURIComponent(tenantId)}\` : "";
    return this.request(\`/v1/telemetry/enforcement-status\${suffix}\`);
  }

  getFleet() {
    return this.request("/api/fleet");
  }

  signupTenant(request) {
    return this.request("/v1/signup/tenant", { method: "POST", body: request });
  }

  getSession({ tenantId = "" } = {}) {
    const suffix = tenantId ? \`?tenant_id=\${encodeURIComponent(tenantId)}\` : "";
    return this.request(\`/v1/auth/session\${suffix}\`);
  }

  acceptInvitation(request) {
    return this.request("/v1/invitations/accept", { method: "POST", body: request });
  }

  inviteMember(tenantId, request) {
    return this.request(\`/v1/tenants/\${encodeURIComponent(tenantId)}/invitations\`, { method: "POST", body: request });
  }

  listMembers(tenantId) {
    return this.request(\`/v1/tenants/\${encodeURIComponent(tenantId)}/members\`);
  }

  updateMemberRoles(tenantId, accountId, request) {
    return this.request(\`/v1/tenants/\${encodeURIComponent(tenantId)}/members/\${encodeURIComponent(accountId)}/roles\`, { method: "POST", body: request });
  }

  removeMember(tenantId, accountId, request = {}) {
    return this.request(\`/v1/tenants/\${encodeURIComponent(tenantId)}/members/\${encodeURIComponent(accountId)}\`, { method: "DELETE", body: request });
  }

  configureIdentityProvider(tenantId, request) {
    return this.request(\`/v1/tenants/\${encodeURIComponent(tenantId)}/identity-providers\`, { method: "PUT", body: request });
  }

  createScimUser(tenantId, request) {
    return this.request("/scim/v2/Users", { method: "POST", body: request, headers: { "x-pollek-tenant-id": tenantId } });
  }

  createScimGroup(tenantId, request) {
    return this.request("/scim/v2/Groups", { method: "POST", body: request, headers: { "x-pollek-tenant-id": tenantId } });
  }

  getBillingUsage(tenantId) {
    return this.request(\`/v1/tenants/\${encodeURIComponent(tenantId)}/billing/usage\`);
  }

  ingestLcpUsageLedger(request) {
    return this.request("/api/lcp/usage-ledgers", { method: "POST", body: request });
  }

  ingestTenantLcpUsageLedger(tenantId, request) {
    return this.request(\`/v1/tenants/\${encodeURIComponent(tenantId)}/lcp/usage-ledgers\`, { method: "POST", body: request });
  }

  updateSubscription(tenantId, request) {
    return this.request(\`/v1/tenants/\${encodeURIComponent(tenantId)}/billing/subscription\`, { method: "POST", body: request });
  }

  listInvoices(tenantId) {
    return this.request(\`/v1/tenants/\${encodeURIComponent(tenantId)}/billing/invoices\`);
  }

  addPaymentMethod(tenantId, request) {
    return this.request(\`/v1/tenants/\${encodeURIComponent(tenantId)}/billing/payment-methods\`, { method: "POST", body: request });
  }

  issueOfflineLicense(tenantId, request = {}) {
    return this.request(\`/v1/tenants/\${encodeURIComponent(tenantId)}/billing/license/issue\`, { method: "POST", body: request });
  }

  sendBillingWebhook(provider, request) {
    return this.request(\`/v1/billing/webhooks/\${encodeURIComponent(provider)}\`, { method: "POST", body: request });
  }

  getKmsHealth() {
    return this.request("/v1/kms/health");
  }

  replayEvents({ since = "", channel = "contract-hub", limit = 100 } = {}) {
    const params = new URLSearchParams();
    if (since) params.set("since", since);
    if (channel) params.set("channel", channel);
    if (limit) params.set("limit", String(limit));
    return this.request(\`/api/events/replay?\${params}\`);
  }

  checkAuthorization(request) {
    return this.request("/api/authz/check", { method: "POST", body: request });
  }

  writeAuthorizationTuple(tuple) {
    return this.request("/api/authz/tuples", { method: "POST", body: tuple });
  }

  getLatestBundle(tenantId) {
    return this.request(\`/v1/tenants/\${encodeURIComponent(tenantId)}/bundles/latest\`);
  }

  getLatestDeviceBundle(tenantId, deviceId, request = {}) {
    return this.request(\`/v1/tenants/\${encodeURIComponent(tenantId)}/devices/\${encodeURIComponent(deviceId)}/bundles/latest\`, { method: "POST", body: request });
  }

  getDeviceCapabilitySnapshot(tenantId, deviceId) {
    return this.request(\`/v1/tenants/\${encodeURIComponent(tenantId)}/devices/\${encodeURIComponent(deviceId)}/capability-snapshot-v2\`);
  }

  listRegistryAgents(tenantId) {
    return this.request(\`/v1/tenants/\${encodeURIComponent(tenantId)}/registry/agents\`);
  }

  listDiscoveryCandidates(tenantId) {
    return this.request(\`/v1/tenants/\${encodeURIComponent(tenantId)}/discovery/candidates\`);
  }

  getBundleManifest(bundleId) {
    return this.request(\`/v1/policy-bundles/\${encodeURIComponent(bundleId)}/manifest\`);
  }

  getBundleArtifact(bundleId) {
    return this.request(\`/v1/policy-bundles/\${encodeURIComponent(bundleId)}/artifact\`);
  }

  signPolicyBundle(bundleId, request) {
    return this.request(\`/api/policy-bundles/\${encodeURIComponent(bundleId)}/sign\`, { method: "POST", body: request });
  }

  generatePolicyDraft(request) {
    return this.request("/api/policy/assist", { method: "POST", body: request });
  }
}

export function createPollekCloudClient(options) {
  return new PollekCloudClient(options);
}
`;
}

export async function generateSdk() {
  const contract = JSON.parse(await readFile(contractPath, "utf8"));
  await mkdir(path.dirname(sdkPath), { recursive: true });
  await writeFile(sdkPath, sdkSource(contract), "utf8");
  console.log(`Generated ${path.relative(rootDir, sdkPath)}`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await generateSdk();
}
